[package]
name = "ast-macros"
description = "Procedural macros backed by ast-core"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]
proc-macro = true

[dependencies]
ast-core = { path = "../ast-core" }
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true
