[package]
name = "rust-transform-macro"
description = "Procedural macros that inspect and transform Rust syntax trees"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
proc-macro = true

[dependencies]
rust-transform = { path = "../rust-transform" }
syn.workspace = true
quote.workspace = true
proc-macro2.workspace = true
