[package]
name = "rust-transform-example"
description = "Exercise crate that uses the transformation macros"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
rust-transform-macro = { path = "../rust-transform-macro" }
rust-transform = { path = "../rust-transform" }
