[package]
name = "ast-core"
description = "Parsing and transformation logic for the ast-macros procedural macros"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true
