[package]
name = "demo"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "=1.0.195", features = ["derive"] }

[target.i686-pc-windows-gnu.dependencies]
winapi = { version = "0.3", features = [
    "winnt",
    "minwindef",
    "windef",
    "winbase",
    "winuser",
    "winerror",
    "handleapi",
    "errhandlingapi",
    "libloaderapi",
    "memoryapi",
    "processthreadsapi",
    "synchapi",
    "fileapi",
    "winreg",
    "shell32",
    "shlobj",
    "gdi32",
    "advapi32",
    "ole32",
    "oleaut32",
    "winsock2",
    "ws2tcpip",
] }